type: object
displayName: GLAccount
description: Object representing a single GLAccount.
properties:
  id:
    type: string
    maxLength: 100
  accountType?:
    type: string
    maxLength: 20
  changedBy:
    type: string
    maxLength: 60
  changedOn:
    type: datetime
  createdBy:
    type: string
    maxLength: 60
  createdOn:
    type: datetime
  customerId:
    type: string
    maxLength: 30
  shortDescription?:
    type: string
    maxLength: 100
  validFrom?:
    type: datetime
  validTo?:
    type: datetime
