type: object
displayName: InvoiceReceipt
description: Object representing a single InvoiceReceipt.
# not complete list of properties
properties:
  key: integer
  bookingDate: datetime
  supplierId:
    type: string
    maxLength: 30
  customerId:
    type: string
    maxLength: 30
  changedBy:
    type: string
    maxLength: 60
    default: "jcadmin"
  changedOn: datetime
  createdBy:
    type: string
    maxLength: 60
    default: "jcadmin"
  createdOn: datetime
  invoiceReceiptId?:
    type: string
    maxLength: 30
  extInvoiceReceiptId?:
    type: string
    maxLength: 255
  invoiceDate: datetime
  periodOfServiceFrom?: datetime
  periodOfServiceTo?: datetime
  statusId:
    type: string
    maxLength: 20
  accountingRecordId?:
    type: string
    maxLength: 30
  referenceInformation?:
    type: string
    maxLength: 140
  dueDate?: datetime
  termsOfPaymentId:
    type: string
    maxLength: 20
  methodOfPaymentId:
    type: string
    maxLength: 20
  termsOfDeliveryId?:
    type: string
    maxLength: 20
  intrastatId:
    type: string
    maxLength: 10
  commentary?:
    type: string
    maxLength: 2000
  currencyId:
    type: string
    maxLength: 3
  orderNumber?:
    type: string
    maxLength: 30

