type: object
displayName: InvoiceReceiptItem
description: Object representing a single InvoiceReceiptItem.
# not complete list of properties
properties:
  key: integer
  changedBy:
    type: string
    maxLength: 60
    default: "jcadmin"
  changedOn: datetime
  createdBy:
    type: string
    maxLength: 60
    default: "jcadmin"
  createdOn: datetime
  productId:
    type: string
    maxLength: 255
  productKey:
    type: string
    maxLength: 255
  orderItemNo: integer
  productDescShort?:
    type: string
    maxLength: 2000
  quantity:
    type: number
    format: double
  uomId:
    type: string
    maxLength: 3
  netPrice?:
    type: number
    format: double
  priceUnit: integer
  extProductId?:
    type: string
    maxLength: 100
  taxId:
    type: string
    maxLength: 60
    default: "0"
  taxRate:
    type: number
    format: double
    default: 0.00
  totalNetPrice?:
    type: number
    format: double
  taxAmount?:
    type: number
    format: double
  totalGrossPrice?:
    type: number
    format: double
  currencyId?:
    type: string
    maxLength: 3

