export const SEARCH_INVOICE_FORM = 'SEARCH_INVOICE_FORM';
export const EDIT_INVOICE_FORM = 'EDIT_INVOICE_FORM';
export const CREATE_INVOICE_FORM = 'EDIT_INVOICE_FORM';
export const INVOICE_ITEM_FORM = 'INVOICE_ITEM_FORM';
