export const INVOICE_ITEMS_LOAD_START = 'INVOICE_ITEMS_LOAD_START';
export const INVOICE_ITEMS_LOAD_SUCCESS = 'INVOICE_ITEMS_LOAD_SUCCESS';
export const INVOICE_ITEMS_LOAD_ERROR = 'INVOICE_ITEMS_LOAD_ERROR';

export const INVOICE_ITEM_CREATE_START = 'INVOICE_ITEM_CREATE_START';
export const INVOICE_ITEM_CREATE_SUCCESS = 'INVOICE_ITEM_CREATE_SUCCESS';
export const INVOICE_ITEM_CREATE_ERROR = 'INVOICE_ITEM_CREATE_ERROR';
