export const INVOICE_IMPORT_STARTED = 'INVOICE_IMPORT_STARTED';
export const INVOICE_CHUNK_IMPORTED = 'INVOICE_CHUNK_IMPORTED';
export const INVOICE_IMPORT_FINISHED = 'INVOICE_IMPORT_FINISHED';
export const INVOICE_IMPORT_FAILED = 'INVOICE_IMPORT_STARTED';
export const INVOICE_IMPORT_CHUNK_SIZE = 10;
export const CLEANUP_IMPORT = 'CLEANUP_IMPORT';
