export const INVOICES_LOAD_START = 'INVOICES_LOAD_START';
export const INVOICES_LOAD_SUCCESS = 'INVOICES_LOAD_SUCCESS';
export const INVOICES_LOAD_ERROR = 'INVOICES_LOAD_ERROR';

export const INVOICE_LOAD_START = 'INVOICE_LOAD_START';
export const INVOICE_LOAD_SUCCESS = 'INVOICE_LOAD_SUCCESS';
export const INVOICE_LOAD_ERROR = 'INVOICE_LOAD_ERROR';

export const INVOICE_CREATE_START = 'INVOICE_CREATE_START';
export const INVOICE_CREATE_SUCCESS = 'INVOICE_CREATE_SUCCESS';
export const INVOICE_CREATE_ERROR = 'INVOICE_CREATE_ERROR';

export const INVOICE_UPDATE_START = 'INVOICE_UPDATE_START';
export const INVOICE_UPDATE_SUCCESS = 'INVOICE_UPDATE_SUCCESS';
export const INVOICE_UPDATE_ERROR = 'INVOICE_UPDATE_ERROR';

export const INVOICE_DELETE_START = 'INVOICE_DELETE_START';
export const INVOICE_DELETE_SUCCESS = 'INVOICE_DELETE_SUCCESS';
export const INVOICE_DELETE_ERROR = 'INVOICE_DELETE_ERROR';

export const INIT_NEW_INVOICE = 'INIT_NEW_INVOICE';

export const EDIT_INVOICE = 'EDIT_INVOICE';
export const INVOICE_UNLOAD = 'INVOICE_UNLOAD';

