queryParameters:
  offset:
    description: Skip over a number of elements by specifying an offset value for the query
    type: number
    required: false
    default: 0
  count:
    description: Limit the number of elements on the response
    type: number
    required: false
    default: 10
