queryParameters:
  sort:
    description: Sort results by specifying sort parameter value as one or multiple separated by , field names. May be optionally preceded by a - to indicate descending order.
    type: string
    required: false
