#%RAML 1.0
title: Invoice
description: Invoice API
version: 1.0.0
baseUri: /api
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS

types: !include schemas/index.raml
traits: !include traits/index.raml

/glAccounts: !include resourceTypes/glAccount.raml
/invoices: !include resourceTypes/invoice.raml
