displayName: GLAccount
get:
  description: List of `GLAccount` objects.
  is:
    [paginable, sortable, queriable]
  queryParameters:
      id?:
        type: string
        description: "Search by id"
      accountType?:
        type: string
        description: "Search by accountType"
      changedBy?:
        type: string
        description: "Search by changedBy"
      changedOn?:
        type: datetime
        description: "Search by changedOn"
      createdBy?:
        type: string
        description: "Search by createdBy"
      createdOn?:
        type: datetime
        description: "Search by createdOn"
      customerId?:
        type: string
        description: "Search by customerId"
      shortDescription?:
        type: string
        description: "Search by shortDescription"
      validFrom?:
        type: datetime
        description: "Search for GLAccount having validFrom greater or equal to specified"
      validTo?:
        type: datetime
        description: "Search for GLAccount having validTo lesser or equal to specified"
  responses:
    200:
      body:
        application/json:
          type: GLAccount[]
          example: !include ../examples/GLAccountsList.json
/{id}:
  uriParameters:
    id:
      type: string
      description: Identifier of a GLAccount.
  get:
    description: Get single `GLAccount` object with given id.
    responses:
      200:
        body:
          application/json:
            type: GLAccount
            example: !include ../examples/GLAccount.json
  put:
    description: Update `GLAccount` with given id.
    body:
      type: GLAccount
      example:
        value:
          accountType: "Example Type"
          shortDescription: "Example Description"
    responses:
      200:
        body:
          application/json:
            type: GLAccount
            example: !include ../examples/GLAccount.json
  delete:
    description: Delete `GLAccount` with given id.
post:
  description: Create `GLAccount` instance.
  body:
    application/json:
      type: GLAccount
      example: !include ../examples/GLAccount.json
  responses:
    200:
      body:
        application/json:
          type: GLAccount
          example: !include ../examples/GLAccount.json
