displayName: InvoiceReceiptItem
get:
  description: List of `InvoiceReceiptItem` objects.
  is:
    [paginable, sortable, queriable]
  responses:
    200:
      body:
        applicaton/json:
          type: InvoiceReceiptItem[]
          example: !include ../examples/InvoiceReceiptItemsList.json
/{id}:
  uriParameters:
    id:
      type: integer
      description: Identifier of an InvoiceReceiptItem.
  get:
    description: Get single `InvoiceReceiptItem` object with given id.
    responses:
      200:
        body:
          application/json:
            type: InvoiceReceiptItem
            example: !include ../examples/InvoiceReceiptItem.json
  put:
    description: Update `InvoiceReceiptItem` with given id.
    body:
      type: InvoiceReceiptItem
      example:
        value:
          netPrice: 100
          quantity: 5
    responses:
      200:
        body:
          application/json:
            type: InvoiceReceiptItem
            example: !include ../examples/InvoiceReceiptItem.json
  delete:
    description: Delete `InvoiceReceiptItem` with given id.
post:
  description: Create `InvoiceReceiptItem` instance.
  body:
    application/json:
      type: InvoiceReceiptItem
      example: !include ../examples/InvoiceReceiptItem.json
  responses:
    200:
      body:
        application/json:
          type: InvoiceReceiptItem
          example: !include ../examples/InvoiceReceiptItem.json
