displayName: InvoiceReceipt
get:
  description: List of `InvoiceReceipt` objects.
  is:
    [paginable, sortable, queriable]
  queryParameters:
    invoiceReceiptId?:
      type: string
      description: "Search by invoiceReceiptId"
    statusId?:
      type: string
      description: "Search by statusId"
    customerId?:
      type: string
      description: "Search by customerId"
  responses:
    200:
      body:
        applicaton/json:
          type: InvoiceReceipt[]
          example: !include ../examples/InvoiceReceiptsList.json
/{id}:
  uriParameters:
    id:
      type: integer
      description: Identifier of an InvoiceReceipt.
  get:
    description: Get single `InvoiceReceipt` object with given id.
    responses:
      200:
        body:
          application/json:
            type: InvoiceReceipt
            example: !include ../examples/InvoiceReceipt.json
  put:
    description: Update `InvoiceReceipt` with given id.
    body:
      type: InvoiceReceipt
      example:
        value:
          statusId: "390"
          commentary: "Example Commentary"
    responses:
      200:
        body:
          application/json:
            type: InvoiceReceipt
            example: !include ../examples/InvoiceReceipt.json
  delete:
    description: Delete `InvoiceReceipt` with given id.
  /items: !include ../resourceTypes/invoiceItems.raml
post:
  description: Create `InvoiceReceipt` instance.
  body:
    application/json:
      type: InvoiceReceipt
      example: !include ../examples/InvoiceReceipt.json
  responses:
    200:
      body:
        application/json:
          type: InvoiceReceipt
          example: !include ../examples/InvoiceReceipt.json
